### ISSUE TITLE
Carbon Roller with wrong sub

### ISSUE THREAD

**Issue by MandL27** [DeviPotato/splatoon-calculator#4]
The calc says the Carbon Roller's sub is Splat Bomb, when it's actually Burst Bomb. I don't know if this affects other weapons.

**Comment by DeviPotato** [comment]
Thanks for the report. Sorry for the belated response, haven't done much work on this project since splatoon hasn't gotten new content in a while. This is a small oversight and an easy fix so I'll push a change soon.

**Comment by MandL27** [comment]
Alright; glad I could report it.
